@CostosPizza_HostAddress = http://localhost:5138

GET {{CostosPizza_HostAddress}}/weatherforecast/
Accept: application/json

###
Get {{ContosoPizza_HostAddress}}/pizza/
Accept: application/json

###
Get {{ContosoPizza_HostAddress}}/pizza/1
Accept: application/json

##
Get {{ContosoPizza_HostAddress}}/pizza/2
Accept: application/json

##
Get {{ContosoPizza_HostAddress}}/pizza/3
Accept: application/json
